apiVersion: apps/v1
kind: Deployment
metadata:
  name: generator-app
  labels:
    app: generator-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: generator-app
  template:
    metadata:
      labels:
        app: generator-app
    spec:
      containers:
      - name:  generator-app
        image: generator-app:latest
        imagePullPolicy: Never  
        ports:
        - containerPort: 8080 