apiVersion: v1
kind: Service
metadata:
  name: jobs-manager-client
spec:
  selector: 
    app: jobs-manager-client
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 80  
  type: ClusterIP  