apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobs-manager
  labels:
    app: jobs-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobs-manager
  template:
    metadata:
      labels:
        app: jobs-manager
    spec:
      containers:
        - name: jobs-manager-container
          image: jobs_manager:latest
          ports:
            - containerPort: 8080
          env:
            - name: ILUM_CORE_URL
              value: http://ilum-core:9888
            - name: ILUM_CORE_VERSION_PATH
              value: /api/v1/

            - name: MINIO_ENDPOINT
              value: http://ilum-minio:9000
            - name: MINIO_USERNAME
              value: minioadmin
            - name: MINIO_PASSWORD
              value: minioadmin
            - name: MINIO_BUCKET
              value: ilum-files
            

            - name: MONGODB_HOST
              value: jobs-manager-mongodb
            - name: MONGODB_DATABASE
              value: jobs_manager_db
            - name: MONGODB_PORT
              value: '27017'
            - name : MONGODB_USERNAME
              value : myroot
            - name : MONGODB_PASSWORD 
              value : mypass

            - name: KAFKA_BOOTSTRAP_SERVERS
              value: ilum-kafka:9092

            - name: QUARTZ_MONGO_URI
              value: mongodb://myroot:mypass@jobs-manager-mongodb:27017
            - name: QUARTZ_MONGO_DATABASE
              value: jobs_manager_db
            