apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobs-manager
  labels:
    app: jobs-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobs-manager
  template:
    metadata:
      labels:
        app: jobs-manager
    spec:
      initContainers:
      - name: wait-for-ilum-core
        image: busybox
        command: ['sh', '-c', 'until nc -z -v -w30 ilum-core 9888; do echo "Waiting for ilum-core..."; sleep 5; done']
      containers:
        - name: jobs-manager-container
          image: delienelu/jobs_manager:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: ILUM_CORE_URL
              value: http://ilum-core:9888
            - name: ILUM_CORE_VERSION_PATH
              value: /api/v1/

            - name: MINIO_ENDPOINT
              value: http://ilum-minio:9000

            - name: MINIO_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: jobs-manager-credentials
                  key: minio-username
            - name: MINIO_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: jobs-manager-credentials
                  key: minio-password
            - name: MINIO_BUCKET
              value: ilum-files
            

            - name: MONGODB_HOST
              value: jobs-manager-mongodb
            - name: MONGODB_DATABASE
              value: jobs_manager_db
            - name: MONGODB_PORT
              value: '27017'
            - name : MONGODB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: jobs-manager-credentials
                  key: mongodb-username
            - name : MONGODB_PASSWORD 
              valueFrom: 
                configMapKeyRef:
                  name: jobs-manager-credentials
                  key: mongodb-password

            - name: KAFKA_BOOTSTRAP_SERVERS
              value: ilum-kafka:9092

            - name: QUARTZ_MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: jobs-manager-credentials
                  key: mongodb-uri
              
            - name: QUARTZ_MONGO_DATABASE
              value: jobs_manager_db
            