apiVersion: v1
kind: ConfigMap
metadata:
  name: jobs-manager-credentials
type: Opaque
data:
  jobs-manager-admin-username: {{ .Values.jobs_manager.admin.username | default "admin" }}
  jobs-manager-admin-password: {{ .Values.jobs_manager.admin.password | default "admin" }}
  jobs-manager-admin-fullname: {{ .Values.jobs_manager.admin.fullname | default "somefullname"}}

  mongodb-username : {{ .Values.mongodb.admin.username | default "mongoadmin"}}
  mongodb-password : {{ .Values.mongodb.admin.password | default "mongoadmin"}}
  mongodb-uri: {{ .Values.mongodb.uri | default "mongodb://mongoadmin:mongoadmin@jobs-manager-mongodb:27017"}}

  minio-username: {{ .Values.minio.admin.username | default "minioadmin"}}
  minio-password: {{ .Values.minio.admin.password | default "minioadmin"}}



