apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobs-manager-mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobs-manager-mongodb
  template:
    metadata:
      labels:
        app: jobs-manager-mongodb
    spec:
      containers:
      - name: jobs-manager-mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom: 
            configMapKeyRef:
              name: jobs-manager-credentials
              key: mongodb-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: jobs-manager-credentials
              key: mongodb-password 
        volumeMounts:
        - name: mongodb-storage
          mountPath: /data/db 
      volumes:
      - name: mongodb-storage
        persistentVolumeClaim:
          claimName: mongodb-pvc